# If upstreamHosts is populated then access is restricted to this list
# unless running in dev mode (-Dmdw.runtime.env=dev).
upstreamHosts:
  - 127.0.0.1
  - 0:0:0:0:0:0:0:1
  
# Auth methods supported include ct (ClearTrust Web Agent) 
# oauth (OAuth2), or jwt (JSON Web Tokens).  Default is jwt.
authMethod: ct

# This is the header we trust to specify the authenticated user id.
# NOTE: This is only secure when upstreamHosts is enforced.
authUserHeader: ct-remote-user

# Allows access to all UI functions and Service APIs permitted for this
# user without authenticating.  Requires "-Dmdw.runtime.env=dev" system property.
devUser: mdwapp

# Auth exclusions are patterns that can be accessed directly
# without authentication even when running with protection 
# (upstreamHosts != null & not in dev mode). 
# In the cases where the pattern accesses a service, it falls to
# the specific service to handle access (i.e. based on HTTP method and/or path)
authExclusions:
  - '/login'
  - '/error'
  - '/js/nav.json'  
  - '/images/*'
  - '/css/*'
  - '/doc/*'
  - '/javadoc/*'
  - '/api/*'
  - '/services/Appsummary'
  - '/services/System/sysInfo'
  - '/services/com/centurylink/mdw/slack'
  
# Headers appended to all HTTP servlet responses.
responseHeaders:
  X-UA-Compatible: IE=Edge
  
# Session timeout in seconds (if not specified, container will govern).
sessionTimeout: 3600

# Allowing any authenticated user means even those not in mdw's db.
allowAnyAuthenticatedUser: false

# Special options for logging
loggingOptions:
  logResponseTimes: false
  logHeaders: false
  logParameters: false  