# https://centurylinkcloud.github.io/mdw/docs/guides/configuration/
app:
  id: {{project}}

database:
  driver: {{database-driver}}
  url: {{database-url}}
  username: {{database-user}}
  password: {{database-password}}
  poolsize: 5
  poolMaxIdle: 3
  validationQuery: select 1 from dual

asset:
  location: {{asset-loc}}

git:
  local.path: .
  remote.url: {{git-remote-url}}
  branch: {{git-branch}}

temp.dir: ./temp

hub.url: http://localhost:8080/mdw

logging:
  level: DEBUG
