repository: "CenturyLinkCloud/mdw"
theme: jekyll-theme-cayman
baseurl: /mdw

markdown: kramdown
highlighter: rouge

help_url: http://centurylinkcloud.github.io/mdw/

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"

name: MDW, Workflow engine, Microservices
description: Feature rich custumizable workflow engine
url: http://centurylinkcloud.github.io/mdw/

logo: /assets/imgages/mdw.png

#timezone: America/Denver

collections:
  docs:
    permalink: /:collection/:path/
    output: true
    
gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
